steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tensorflow-base', '.', '-f', 'Dockerfile.base' ]
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tensorflow-base']
images:
  - 'gcr.io/$PROJECT_ID/tensorflow-base'
