steps:
  # Retrieve the exported model by the training
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', '-r', '${_EXPORT_BUCKET}', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/predict', '.' ]
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/predict']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'predict'
      - '--image=gcr.io/$PROJECT_ID/predict'
      - '--region=us-central1'
      - '--platform=managed'
images:
  - 'gcr.io/$PROJECT_ID/predict'
substitutions:
    _EXPORT_BUCKET: gs://my-bucket/path/to/export/exporter
